### ISSUE TITLE
CheckList (Due 11/20)

### ISSUE THREAD

**Issue by byeoli** [JECH2/GameDesignProject_KAIST#57]
**금요일까지 완성되어야하는 것 LIST**

- [x] 1) Target 특정 위치에 세우기 @HajunKim **수**

- [x] 2) Target Collider 만들기 @HajunKim **수**

- [x] **3) Target의 Collider에 닿아서 -> 플레이어의 마이크 켜지고 -> 플레이어가 소리를 내면 -> 소리에 따라 -> Target에 색칠해지기 @HajunKim **수****

- [x] **4) Target Region(Aura)에 들어오면 들어온거 알 수 있게끔 (화면 스크린색? 변화?) **수**
        - Aura도 활성화/비활성화에 따라 status가 달라지면어떨까?**

- [x] 5) Target 색칠할때 수
        - 노트에 따른 색 변화 : Target 색의 alpha 값으로 조절하여 색 변화 보여주기 
        - 프레임 업데이트할때마다 > Collision note가 맞으면 > alpha값을 특정 갭만큼 계속 올리기 
                                                     > Collision note 안맞으면 > alpha값 특정 값만큼 빼기 

- [x] 6) Target 색칠 후 완료되었을 때 > Activation된 상태 표시 **수**

- [x] **7) 플레이어가 Input으로 넣는 노트에 따른 색을 하단에 표시해주기** 

- [x] **8) Asset 적용하기 (배경 & 사운드 이펙트) **목**
          - 사운드 이펙트 @JECH2 
          - 배경**

- [x] **10) 카메라 movement 관련 알아보기 @byeoli 
        - 2명의 player 사이 거리 계산 (position 값으로) 해서 거리가 특정 값 이상으로 멀어지면 카메라 zoom out 하는 방법?**
- [x] 9) Spatial Sound 구현하는 방법 찾기 @JECH2 
       - Target 생성 위치 알려주는 Sound : 기분 나쁜 소리로 구현할 수 있게끔 (전자파 소리, 찌릿찌릿, 찌직찌직, 간격을 두고)

- [x] **11) PlayerHealth 나타나는 Heart 모양 ----> 음표 모양으로 바꾸기 @byeoli **수**
          - 그린 듯한 느낌의 음표 png 찾기** 

- [x] **12) Balance 맞추기 (죽는 속도, 쏘는 속도 등등) **목****

- [x] 피피티 만들기 !

**Comment by JECH2** [comment]
생각해보니 별건 아닌데 나중에 게임 들어가기 전 메인씬 같은거도 구현해야할듯..! 환경설정이나

**Comment by byeoli** [comment]
10) Camera Movement 
참고 자료 
- Target Following + Mouse 사용 (Zoom In-Out) <- Min, Max Zoom-In/Out 존재함 https://gamedev.stackexchange.com/questions/182743/move-camera-closer-zoom-in-out-to-object-that-is-being-followed-unity

**Comment by byeoli** [comment]
Spatial sound 
- 두명이 각자 위치에 따라 다른 spatial sound를 듣는건 불가 
- 현재 : player1에게 audio가 set 되어있는 상태 ! 
-----------> 완료 !

**Comment by JECH2** [comment]
- 사운드 에셋 적용 완료(별이)
- 배경 에셋을 어떻게 적용시킬지 생각해보기 : 현재 배경 에셋과 비주얼 이펙트 에셋 다 다운받아서 집어넣었습니다! see #48

**Comment by JECH2** [comment]
![image](https://user-images.githubusercontent.com/26477914/99564714-2266c000-2a0e-11eb-80f7-353b35808aeb.png)
땅바닥 메쉬 콜리젼(floor의 mesh collider)만 처리하면 마음껏 새로 적용한 맵을 플레이어가 돌아다닐 수 있을 듯 합니다!

**Comment by byeoli** [comment]
**20201120 FEEDBACK from NC/Prof**

**Main Problem : 게임내에 [ 전투 부분 & 하모니 부분 ] 이 극명하게 분리된 게임으로 보임 ! 아예 다른 게임 두개를 그냥 섞은 것 같다 !** 
--> 음 넣는 부분을 Target에 다가가는 과정(shooting/attacking/defensing) 속에 연계되게끔 풀어넣어보자 ! 
--> [Prof] 상용성보다 게임의 새로운 재미요소 발굴 ! 이 목표이다 ! 우리는 대학원생이다 ! 

 * 재미요소는 어디서 더 증대시킬 수 있는지 ? 생각해보기
 
+ [NC] 정확한 음정 detecting이 중요한가? 재미를 위해 꼭 이게 필요하지 않을 수도 있다. 
+ [Prof] Enemy도 Sound를 가져? (boss만이라도?)
+ [NC] 두 플레이어를 뭉치게(서로 최대한 같이 붙어다니게) 만드는 요인을 만들자 ! 
    - 플레이어간 사이 거리가 좁으면 Enemy의 체력에 영향을 미친다? 
    - 둘이 함께하여 시너지를 내는 요소가 있다면? (둘이 같은 행동을 하게끔 유도) 
+ [NC] Enemy type의 Variation 
    - Boss의 등장
    - 너무 많은 X, 한 컨셉 정도만 중점적으로 ! 
+ [NC] 비누방울 어택 ?
